"""Install the pinned upstream bridge inside this project. Requires git and uv."""
from pathlib import Path
import json
import shutil
import subprocess

root = Path(__file__).resolve().parents[1]
repo = root / '.local-tools/blender-mcp'
venv = root / '.local-tools/blender-venv'
revision = '5f8ddaf6e987c4aa0c3467fcc548838b28f64477'
for tool in ('git', 'uv'):
    if not shutil.which(tool):
        raise SystemExit(f'Install {tool} first')
if not repo.exists():
    subprocess.run(['git', 'clone', 'https://github.com/ahujasid/blender-mcp.git', str(repo)], check=True)
    subprocess.run(['git', '-C', str(repo), 'checkout', revision], check=True)
head = subprocess.check_output(['git', '-C', str(repo), 'rev-parse', 'HEAD'], text=True).strip()
if head != revision:
    raise SystemExit('Existing bridge checkout differs; inspect it before changing versions')
source = repo / 'addon.py'
text = source.read_text()
old = 'if bpy.app.background:'
new = 'if bpy.app.background and os.environ.get("BBN_MAIN_THREAD_DRIVER") != "1":'
if new not in text:
    if text.count(old) != 1:
        raise SystemExit('Upstream guard changed; review headless-support.patch')
    source.write_text(text.replace(old, new))
if not venv.exists():
    subprocess.run(['uv', 'venv', str(venv)], check=True)
subprocess.run(['uv', 'pip', 'install', '--python', str(venv / 'bin/python'), '-e', str(repo)], check=True)
config = root / '.codex/config.toml'
config.parent.mkdir(exist_ok=True)
content = f'''# Project-local Blender MCP; generated by scripts/setup_blender.py.
[mcp_servers.blender]
command = {json.dumps(str(venv / 'bin/blender-mcp'))}
args = []
startup_timeout_sec = 30
tool_timeout_sec = 180
[mcp_servers.blender.env]
BLENDER_HOST = "127.0.0.1"
BLENDER_PORT = "9876"
BLENDER_MCP_DISABLE_TELEMETRY = "1"
BLENDER_MCP_SAFE_MODE = "1"
'''
if not config.exists() or config.read_text().startswith('# Project-local Blender MCP'):
    config.write_text(content)
else:
    raise SystemExit('Existing Codex config preserved. Add the Blender block manually.')
print('Setup complete. Run npm run blender:start, then npm run blender:check.')
